import { PrismaClient } from "../src/generated/prisma";
import { PrismaPg } from "@prisma/adapter-pg";

const adapter = new PrismaPg({
  connectionString: process.env.DATABASE_URL!,
});

const prisma = new PrismaClient({ adapter });

async function main() {
  await prisma.college.deleteMany();

  await prisma.college.createMany({
    data: [
      {
        name: "IIT Delhi",
        location: "Delhi",
        fees: 200000,
        rating: 4.8,
        courses: ["B.Tech", "M.Tech", "PhD"],
        overview: "Premier engineering institute in India.",
        placements: {
          avgSalary: 1800000,
          placementRate: 95,
          topRecruiters: ["Google", "Microsoft", "Amazon"],
        },
      },
      {
        name: "IIT Bombay",
        location: "Mumbai",
        fees: 210000,
        rating: 4.9,
        courses: ["B.Tech", "M.Tech", "MBA"],
        overview: "Top ranked technical university in India.",
        placements: {
          avgSalary: 2000000,
          placementRate: 97,
          topRecruiters: ["Apple", "Goldman Sachs", "McKinsey"],
        },
      },
      {
        name: "IIT Kanpur",
        location: "Kanpur",
        fees: 195000,
        rating: 4.7,
        courses: ["B.Tech", "M.Tech", "PhD"],
        overview: "Known for research and innovation.",
        placements: {
          avgSalary: 1700000,
          placementRate: 93,
          topRecruiters: ["Intel", "Adobe", "Qualcomm"],
        },
      },
      {
        name: "NIT Trichy",
        location: "Tiruchirappalli",
        fees: 150000,
        rating: 4.5,
        courses: ["B.Tech", "M.Tech"],
        overview: "Top NIT with excellent placements.",
        placements: {
          avgSalary: 1200000,
          placementRate: 90,
          topRecruiters: ["TCS", "Infosys", "Wipro"],
        },
      },
      {
        name: "BITS Pilani",
        location: "Pilani",
        fees: 450000,
        rating: 4.6,
        courses: ["B.Tech", "M.Tech", "MBA"],
        overview: "Premier private engineering college.",
        placements: {
          avgSalary: 1500000,
          placementRate: 92,
          topRecruiters: ["Samsung", "Oracle", "Cisco"],
        },
      },
      {
        name: "VIT Vellore",
        location: "Vellore",
        fees: 180000,
        rating: 4.2,
        courses: ["B.Tech", "M.Tech", "MBA"],
        overview: "Large private university with good industry connect.",
        placements: {
          avgSalary: 800000,
          placementRate: 85,
          topRecruiters: ["TCS", "Cognizant", "Capgemini"],
        },
      },
      {
        name: "IIT Madras",
        location: "Chennai",
        fees: 205000,
        rating: 4.9,
        courses: ["B.Tech", "M.Tech", "PhD"],
        overview: "Ranked #1 in NIRF engineering category.",
        placements: {
          avgSalary: 2100000,
          placementRate: 96,
          topRecruiters: ["Google", "Facebook", "JP Morgan"],
        },
      },
      {
        name: "Delhi Technological University",
        location: "Delhi",
        fees: 120000,
        rating: 4.1,
        courses: ["B.Tech", "M.Tech", "MBA"],
        overview: "Top state engineering university in Delhi.",
        placements: {
          avgSalary: 900000,
          placementRate: 82,
          topRecruiters: ["Deloitte", "Accenture", "HCL"],
        },
      },
      {
        name: "SRM Institute",
        location: "Chennai",
        fees: 200000,
        rating: 3.9,
        courses: ["B.Tech", "MBA", "BCA"],
        overview: "Large private university with diverse programs.",
        placements: {
          avgSalary: 700000,
          placementRate: 78,
          topRecruiters: ["TCS", "Wipro", "Infosys"],
        },
      },
      {
        name: "Jadavpur University",
        location: "Kolkata",
        fees: 80000,
        rating: 4.4,
        courses: ["B.Tech", "M.Tech", "PhD"],
        overview: "Premier state university in West Bengal.",
        placements: {
          avgSalary: 1000000,
          placementRate: 88,
          topRecruiters: ["IBM", "Tata Motors", "L&T"],
        },
      },
      {
        name: "IIT Kharagpur",
        location: "Kharagpur",
        fees: 190000,
        rating: 4.7,
        courses: ["B.Tech", "M.Tech", "MBA", "PhD"],
        overview: "Oldest and largest IIT in India.",
        placements: {
          avgSalary: 1600000,
          placementRate: 94,
          topRecruiters: ["Microsoft", "Amazon", "Tesla"],
        },
      },
      {
        name: "Manipal Institute of Technology",
        location: "Manipal",
        fees: 350000,
        rating: 4.0,
        courses: ["B.Tech", "M.Tech"],
        overview: "Well known private engineering college.",
        placements: {
          avgSalary: 750000,
          placementRate: 80,
          topRecruiters: ["Infosys", "Wipro", "HCL"],
        },
      },
      {
        name: "PSG College of Technology",
        location: "Coimbatore",
        fees: 100000,
        rating: 4.3,
        courses: ["B.Tech", "M.Tech", "MBA"],
        overview: "Top autonomous college in Tamil Nadu.",
        placements: {
          avgSalary: 850000,
          placementRate: 86,
          topRecruiters: ["Zoho", "TCS", "Cognizant"],
        },
      },
      {
        name: "NIT Warangal",
        location: "Warangal",
        fees: 145000,
        rating: 4.4,
        courses: ["B.Tech", "M.Tech"],
        overview: "One of the top NITs in South India.",
        placements: {
          avgSalary: 1100000,
          placementRate: 89,
          topRecruiters: ["Google", "Amazon", "Microsoft"],
        },
      },
      {
        name: "IIIT Hyderabad",
        location: "Hyderabad",
        fees: 300000,
        rating: 4.6,
        courses: ["B.Tech", "M.Tech", "PhD"],
        overview: "Top IIIT focused on research and AI.",
        placements: {
          avgSalary: 1800000,
          placementRate: 95,
          topRecruiters: ["Google", "Microsoft", "Adobe"],
        },
      },
      {
        name: "Amity University",
        location: "Noida",
        fees: 280000,
        rating: 3.7,
        courses: ["B.Tech", "MBA", "BCA", "BBA"],
        overview: "Large private university with many programs.",
        placements: {
          avgSalary: 600000,
          placementRate: 72,
          topRecruiters: ["TCS", "Wipro", "Accenture"],
        },
      },
      {
        name: "IIT Roorkee",
        location: "Roorkee",
        fees: 198000,
        rating: 4.7,
        courses: ["B.Tech", "M.Tech", "MBA", "PhD"],
        overview: "Oldest technical institution in Asia.",
        placements: {
          avgSalary: 1650000,
          placementRate: 93,
          topRecruiters: ["Samsung", "Nvidia", "Intel"],
        },
      },
      {
        name: "Thapar Institute",
        location: "Patiala",
        fees: 320000,
        rating: 4.1,
        courses: ["B.Tech", "M.Tech"],
        overview: "Private deemed university in Punjab.",
        placements: {
          avgSalary: 850000,
          placementRate: 83,
          topRecruiters: ["TCS", "Infosys", "HCL"],
        },
      },
      {
        name: "Anna University",
        location: "Chennai",
        fees: 75000,
        rating: 4.2,
        courses: ["B.Tech", "M.Tech", "PhD"],
        overview: "Top state technical university in Tamil Nadu.",
        placements: {
          avgSalary: 750000,
          placementRate: 81,
          topRecruiters: ["Zoho", "Cognizant", "TCS"],
        },
      },
      {
        name: "BIT Mesra",
        location: "Ranchi",
        fees: 160000,
        rating: 3.8,
        courses: ["B.Tech", "M.Tech", "MBA"],
        overview: "Private deemed university in Jharkhand.",
        placements: {
          avgSalary: 650000,
          placementRate: 75,
          topRecruiters: ["Infosys", "Wipro", "TCS"],
        },
      },
      {
        name: "IIT Guwahati",
        location: "Guwahati",
        fees: 192000,
        rating: 4.6,
        courses: ["B.Tech", "M.Tech", "PhD"],
        overview: "Premier IIT in Northeast India.",
        placements: {
          avgSalary: 1500000,
          placementRate: 91,
          topRecruiters: ["Amazon", "Flipkart", "Ola"],
        },
      },
      {
        name: "Pune Institute of Computer Technology",
        location: "Pune",
        fees: 90000,
        rating: 4.0,
        courses: ["B.Tech", "M.Tech"],
        overview: "Top autonomous college in Pune.",
        placements: {
          avgSalary: 720000,
          placementRate: 80,
          topRecruiters: ["Persistent", "Infosys", "TCS"],
        },
      },
      {
        name: "COEP Technological University",
        location: "Pune",
        fees: 85000,
        rating: 4.2,
        courses: ["B.Tech", "M.Tech"],
        overview: "One of oldest engineering colleges in Asia.",
        placements: {
          avgSalary: 800000,
          placementRate: 84,
          topRecruiters: ["Cummins", "KPIT", "Infosys"],
        },
      },
      {
        name: "NIT Surathkal",
        location: "Mangalore",
        fees: 148000,
        rating: 4.3,
        courses: ["B.Tech", "M.Tech"],
        overview: "Top NIT on West Coast of India.",
        placements: {
          avgSalary: 1050000,
          placementRate: 87,
          topRecruiters: ["Google", "Amazon", "Flipkart"],
        },
      },
      {
        name: "Kalinga Institute of Industrial Technology",
        location: "Bhubaneswar",
        fees: 220000,
        rating: 3.9,
        courses: ["B.Tech", "MBA", "MCA"],
        overview: "Deemed university in Odisha.",
        placements: {
          avgSalary: 680000,
          placementRate: 76,
          topRecruiters: ["TCS", "Wipro", "HCL"],
        },
      },
      {
        name: "IIT Hyderabad",
        location: "Hyderabad",
        fees: 196000,
        rating: 4.5,
        courses: ["B.Tech", "M.Tech", "PhD"],
        overview: "New IIT with strong research focus.",
        placements: {
          avgSalary: 1400000,
          placementRate: 90,
          topRecruiters: ["Microsoft", "Qualcomm", "Texas Instruments"],
        },
      },
      {
        name: "Symbiosis Institute of Technology",
        location: "Pune",
        fees: 260000,
        rating: 3.8,
        courses: ["B.Tech", "MBA"],
        overview: "Private university under Symbiosis group.",
        placements: {
          avgSalary: 650000,
          placementRate: 74,
          topRecruiters: ["Accenture", "Capgemini", "L&T"],
        },
      },
      {
        name: "Chandigarh University",
        location: "Chandigarh",
        fees: 170000,
        rating: 3.9,
        courses: ["B.Tech", "MBA", "BCA"],
        overview: "Fast growing private university in Punjab.",
        placements: {
          avgSalary: 620000,
          placementRate: 77,
          topRecruiters: ["TCS", "Infosys", "Wipro"],
        },
      },
      {
        name: "IIT BHU Varanasi",
        location: "Varanasi",
        fees: 194000,
        rating: 4.5,
        courses: ["B.Tech", "M.Tech", "PhD"],
        overview: "IIT located in historic city of Varanasi.",
        placements: {
          avgSalary: 1350000,
          placementRate: 91,
          topRecruiters: ["Amazon", "Uber", "Goldman Sachs"],
        },
      },
      {
        name: "Vellore Institute of Technology Chennai",
        location: "Chennai",
        fees: 185000,
        rating: 4.1,
        courses: ["B.Tech", "M.Tech", "MBA"],
        overview: "VIT Chennai campus with strong industry ties.",
        placements: {
          avgSalary: 820000,
          placementRate: 83,
          topRecruiters: ["Cognizant", "TCS", "Zoho"],
        },
      },
    ],
  });

  console.log("✅ 30 colleges seeded successfully");
}

main()
  .catch(console.error)
  .finally(() => prisma.$disconnect());